# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='testPhoto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
