# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 06:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0004_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacity',
            name='model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='answer.PhoneModel'),
        ),
        migrations.AddField(
            model_name='phonemodel',
            name='maker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='answer.Maker'),
        ),
    ]
