# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0006_auto_20170812_2355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('currentMonth', models.TextField(default='')),
                ('currentRate', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='phonemodel',
            name='factoryPrice',
            field=models.IntegerField(default=0),
        ),
    ]
